// packages/frontend/components/AppFooter.vue
<template>
  <footer class="d-flex flex-column flex-sm-row justify-content-around mt-2 py-3 px-2 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">© 2023 Privacy and Scaling Explorations</p>

    <ul class="nav col-md-4 justify-content-end px-3">
      <li class="nav-item">
        <NuxtLink to="/" class="nav-link">Home</NuxtLink>
      </li>
    </ul>
  </footer>
</template>

<style>
p {
  vertical-align: middle;
}

.nav-link {
  padding: 0;
}
</style>

// packages/frontend/src/routes/AppFooter.svelte
<div class="container-fluid">
	<footer class="py-3 my-4">
		<ul class="nav justify-content-center border-bottom pb-3 mb-3">
			<li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Home</a></li>
			<li class="nav-item">
				<a href="/signup" class="nav-link px-2 text-body-secondary">Signup</a>
			</li>
			<li class="nav-item"><a href="/login" class="nav-link px-2 text-body-secondary">Login</a></li>
			<li class="nav-item"><a href="/chat" class="nav-link px-2 text-body-secondary">Chat</a></li>
			<li class="nav-item"><a href="/about" class="nav-link px-2 text-body-secondary">About</a></li>
		</ul>
		<p class="text-center text-body-secondary">© 2023 Privacy & Scaling Explorations</p>
	</footer>
</div>
